### ISSUE TITLE
Page title function not working with new plugin

### ISSUE THREAD

**Issue by mrsminkie** [BuddyForms/BuddyForms-Advanced-Form-Elements#1]
This function is not working with the new plugin. It grabs the hierarchical taxonomy terms and creates the page title on save:

`<?php
add_action('save_post', 'update_term_title');
function update_term_title($post_id)
{
if(defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) 
    return;
if(!current_user_can('edit_post', $post_id))
    return;

$terms = wp_get_post_terms($post_id, 'car');

if(empty($terms))
    return;

$parent = $child = $grandchild = false;
$parent_id = $child_id = $grandchild_id = 0;

// Find parent
foreach($terms as $term)
{
    if(!$term->parent)
    {
        $parent = $term->name;
        $parent_id = $term->term_id;
        break;
    }
}
// Find child
foreach($terms as $term)
{
    if($term->parent == $parent_id)
    {
        $child = $term->name;
        $child_id = $term->term_id;
        break;
    }
}
// Find grandchild
foreach($terms as $term)
{
    if($term->parent == $child_id)
    {
        $grandchild = $term->name;
        $grandchild_id = $term->term_id;
        break;
    }
}

$title = trim( $parent . ' ' . $child . ' ' . $grandchild );

remove_action('save_post', 'update_term_title');
$update = array(
    'ID'=>$post_id,
    'post_name'=>sanitize_title_with_dashes($title),
    'post_title'=>$title
);
wp_update_post($update);
add_action('save_post', 'update_term_title');
}
?>`

**Comment by svenl77** [comment]
I have created a gist for this function and will do the modifications in this gist to make it work with BuddyForms.
https://gist.github.com/svenl77/f2ba7cd823d705deea00

BuddyForms offers a Hook _bf_update_editpost_title_ to change the title during form submission.

**Comment by mrsminkie** [comment]
I'm not quite sure what that means, but I'm sure I'll learn!

I know there is a hook, and I tried that, but couldn't get it working so I ended up going down this route which did finally work. I tried MANY different functions! I didn't have a life for 3 days over this thing :)

**Comment by svenl77** [comment]
I was able to run this script successfully.

I have added the correct hook to make it work in the front end 

add_action('buddyforms_after_save_post', 'update_term_title', 10, 1);

I have also comment out line 9 and 8. This only works in the backend. IF you want to check capabilities in the front end you need to check for the BuddyForms capabilities 

I have changed cat to product category and its working fine for me product_cat. change "product_cat" to your taxonomy.
